[[plugins]]
repository = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repository = 'groenewege/vim-less'
on_ft = ['less']

[[plugins]]
repository = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repository = 'hallison/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repository = 'motemen/hatena-vim'
on_ft = ['hatena']

[[plugins]]
repository = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repository = 'pangloss/vim-javascript'
on_ft = ['typescript', 'javascript']

[[plugins]]
repository = 'vim-perl/vim-perl'
on_ft = ['perl']

[[plugins]]
repository = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repository = 'davidoc/taskpaper.vim'
on_ft = ['taskpaper']

[[plugins]]
repository = 'motemen/tap-vim'
on_ft = ['perl']

[[plugins]]
repository = 'eagletmt/ghcmod-vim'
external_commands = 'ghc-mod'
on_ft = ['haskell']

[[plugins]]
repository = 'eagletmt/ghci-vim'
external_commands = ['ghc']
on_ft = ['haskell']

[[plugins]]
repository = 'eagletmt/neco-ghc'
on_ft = ['haskell']
external_commands = ['ghc', 'ghc-mod']

[[plugins]]
repository = 'itchyny/vim-haskell-indent'
on_ft = ['haskell']

[[plugins]]
repository = 'Rip-Rip/clang_complete'
on_ft = ['objc']
build = 'make'

[[plugins]]
repository = 'mustache/vim-mustache-handlebars'
on_ft = ['mustache', 'handlebars']

[[plugins]]
repository = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repository = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repository = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repository = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repository = 'kazuho/p5-text-microtemplate'
name = 'text-microtemplate'
rtp = 'contrib/vim'

[[plugins]]
repository = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repository = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repository = 'mattn/emmet-vim'
on_ft = ['html', 'haml', 'slim', 'css', 'tt2html']

[[plugins]]
repository = 'sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']

[[plugins]]
repository = 'thinca/vim-ref'
on_cmd = ['Ref']
on_unite = ['ref/man', 'ref/perldoc']

[[plugins]]
repository = 'haya14busa/incsearch.vim'
on_map = ['<Plug>']

[[plugins]]
repository = 'h1mesuke/vim-alignta'
on_cmd = ['Alignta']

[[plugins]]
repository = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repository = 'motemen/xslate-vim'
on_ft = ['xslate']

[[plugins]]
repository = 'Shougo/neomru.vim'
on_unite = ['file_mru']
