[[plugins]]
repository = 'rhysd/vim-operator-surround'
on_map = ['<Plug>(operator-surround-']

[[plugins]]
repository = 'haya14busa/vim-operator-flashy'
on_map = ['<Plug>(operator-flashy']

[[plugins]]
repository = 'emonkak/vim-operator-comment'
on_map = ['<Plug>(operator-comment)', '<Plug>(operator-uncomment)']
