dotfiles:
  - .bundle
  - .caprc
  - .gemrc
  - .gitconfig
  - .global.gitignore
  - .my.cnf
  - .powenv
  - .proverc
  - .pryrc
  - .screenrc
  - .slate.d
  - .slate.js
  - .tigrc
  - .tmux.conf
  - .uim
  - .vim
  - .zsh.d
  - .zshenv
  - .zshrc
