[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'machakann/vim-textobj-delimited'
depends = ['kana/vim-textobj-user']

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = ['kana/vim-textobj-user']

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = ['kana/vim-textobj-user']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
vim_version = '7.3.885'
disabled = '!has("lua")'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'tyru/current-func-info.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'kana/vim-smartchr'

[[plugins]]
repo = 'sickill/vim-pasta'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make -f make_mac.mak'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/eskk.vim'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = "haya14busa/vim-signjk-motion"

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'aereal/vim-magica-colors'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'hail2u/h2u_colorscheme'

[[plugins]]
repo = 'muratas/vim-andon'

[[plugins]]
repo = 'ajh17/Spacegray.vim'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'rhysd/vim-color-splatoon'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'scheakur/vim-scheakur'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
